/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.ventanasEliminar;

import controlador.AsignaturaControl;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Asignatura;

/**
 *
 * @author Andy Abad
 */
public class AsignaturaEliminarVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form AsignaturaEliminarVentana2
     */
    public AsignaturaEliminarVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Eliminar Asignatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("Ingrese el Codigo: ");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Horas", "Horas de Practica", "Modalidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().equals(""))
        {
            this.setActualizarTabla();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int llave=JOptionPane.showConfirmDialog(this,
                "Esta seguro que sea eliminar la Asignatura",
                "Confirmar eliminar Asignatura",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if(llave==0)
        {
            try{
                asignaturaControl.eliminarAsignatura(jTextField1.getText());
                this.setActualizarTablaDefecto();
                jTextField1.setText("");
                JOptionPane.showMessageDialog(this,
                        "La asignatura se elimino con exito",
                        "Mensaje de Informacion",JOptionPane.INFORMATION_MESSAGE);
            }catch(NullPointerException ex)
            {
                JOptionPane.showMessageDialog(this,
                        "La asignatura con el codigo:("+jTextField1.getText()+") no existe",
                        "Eliminar asignatura",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setLenguajeAsignaturaEliminarVentana(ResourceBundle resourceBundle)
    {
        this.resourceBundle=resourceBundle;
        jLabel1.setText(resourceBundle.getString("JLABELAEV1"));
        jLabel2.setText(resourceBundle.getString("JLABELAEV2"));
        jButton1.setText(resourceBundle.getString("JBUTTON4"));
        jButton2.setText(resourceBundle.getString("JBUTTON5"));
        this.setActualizarTablaDefecto();
    }
    
    public void setActualizarTablaDefecto()
    {
        String[] encabezado=new String[5];
        encabezado[0]=resourceBundle.getString("JTABLETAV1");
        encabezado[1]=resourceBundle.getString("JTABLETAV2");
        encabezado[2]=resourceBundle.getString("JTABLETAV3");
        encabezado[3]=resourceBundle.getString("JTABLETAV4");
        encabezado[4]=resourceBundle.getString("JTABLETAV5");
        
        var datos=new Object[1][5];
        
        TableModel modeloTabla=new DefaultTableModel(datos,encabezado);
        jTable1.setModel(modeloTabla);
    }
    public void setActualizarTabla()
    {
        String[] encabezado=new String[5];
        encabezado[0]=resourceBundle.getString("JTABLETAV1");
        encabezado[1]=resourceBundle.getString("JTABLETAV2");
        encabezado[2]=resourceBundle.getString("JTABLETAV3");
        encabezado[3]=resourceBundle.getString("JTABLETAV4");
        encabezado[4]=resourceBundle.getString("JTABLETAV5");
        
        var datos=new Object[1][5];
        Asignatura asignatura=asignaturaControl.listar().get(asignaturaControl.buscarAsignaturaPorCodigo(jTextField1.getText()));
        datos[0][0]=asignatura.getCodigoAsignatura();
        datos[0][1]=asignatura.getNombre();
        datos[0][2]=asignatura.getHoras();
        datos[0][3]=asignatura.getHorasPractica();
        datos[0][4]=asignatura.getModalidad();
        
        TableModel modeloTabla=new DefaultTableModel(datos,encabezado);
        jTable1.setModel(modeloTabla);
        
    }
    AsignaturaControl asignaturaControl=new AsignaturaControl();
    ResourceBundle resourceBundle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
