/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.ventanasEliminar;

import controlador.AsignaturaControl;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Asignatura;
import modelo.Carrera;
import modelo.Profesor;

/**
 *
 * @author Andy Abad
 */
public class ProfesorEliminarVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form AsignaturaEliminarVentana2
     */
    public ProfesorEliminarVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Eliminar Profesor");

        jLabel2.setText("Ingrese el Codigo de la Asignatura: ");

        jLabel3.setText("Ingrese el Codigo de Carrera: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Correo", "Titulo", "Fecha de Nacimiento", "Anios de trabajo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            this.setActualizarTabla();
        }catch(RuntimeException ex)
        {
            JOptionPane.showMessageDialog(this,"El profesor con el codigo:("+
                    jTextField2.getText()+") no existe","Error eliminar Profesor",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int llave=JOptionPane.showConfirmDialog(this,
                "Esta seguro que desea eliminar la profesor","Eliminar la profesor",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
        if(llave==0)
        {
            try
            {
                asignaturaControl.eliminarProfesor(jTextField1.getText(),jTextField2.getText());
                this.setActualizarTablaDefecto();
                jTextField1.setText("");
                jTextField2.setText("");
                JOptionPane.showMessageDialog(null,"El Profesor se elimino con exito",
                        "Mensaje de informacion",JOptionPane.INFORMATION_MESSAGE);
            }catch(NullPointerException ex)
            {
                JOptionPane.showMessageDialog(this,
                        "El profesor con el codigo:("+jTextField1.getText()+") no existe",
                        "Eliminar Profesor",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setLenguajeProfesorEliminarVentana(ResourceBundle resourceBundle)
    {
        this.resourceBundle=resourceBundle;
        jLabel1.setText(resourceBundle.getString("JLABELPEV1"));
        jLabel2.setText(resourceBundle.getString("JLABELPEV2"));
        jLabel3.setText(resourceBundle.getString("JLABELPEV3"));
        jButton1.setText(resourceBundle.getString("JBUTTON4"));
        jButton2.setText(resourceBundle.getString("JBUTTON5"));
        this.setActualizarTablaDefecto();
    }
    
    public void setActualizarTablaDefecto()
    {
        String[] encabezado=new String[6];
        encabezado[0]=resourceBundle.getString("JTABLETPV1");
        encabezado[1]=resourceBundle.getString("JTABLETPV2");
        encabezado[2]=resourceBundle.getString("JTABLETPV3");
        encabezado[3]=resourceBundle.getString("JTABLETPV4");
        encabezado[4]=resourceBundle.getString("JTABLETPV5");
        encabezado[5]=resourceBundle.getString("JTABLETPV6");
        
        var datos=new Object[1][6];
        
        TableModel modeloTabla=new DefaultTableModel(datos,encabezado);
        jTable1.setModel(modeloTabla);
    }
    public void setActualizarTabla()
    {
        String[] encabezado=new String[6];
        encabezado[0]=resourceBundle.getString("JTABLETPV1");
        encabezado[1]=resourceBundle.getString("JTABLETPV2");
        encabezado[2]=resourceBundle.getString("JTABLETPV3");
        encabezado[3]=resourceBundle.getString("JTABLETPV4");
        encabezado[4]=resourceBundle.getString("JTABLETPV5");
        encabezado[5]=resourceBundle.getString("JTABLETPV6");
        
        var datos=new Object[1][6];
        Asignatura asignatura=asignaturaControl.listar().get(asignaturaControl.buscarAsignaturaPorCodigo(jTextField1.getText()));
        Profesor profesor=asignatura.getProfesorList().get(asignaturaControl.buscarProfesorPorCodigo(jTextField1.getText(),jTextField2.getText()));
        datos[0][0]=profesor.getCodigo();
        datos[0][1]=profesor.getNombre();
        datos[0][2]=profesor.getCorreo();
        datos[0][3]=profesor.getTitulo();
        datos[0][4]=profesor.getDiaNacimiento()+"/"+profesor.getMesNacimiento()+"/"+profesor.getAnioNacimiento();
        datos[0][5]=profesor.getAniosTrabajo();
        
        TableModel modeloTabla=new DefaultTableModel(datos,encabezado);
        jTable1.setModel(modeloTabla);
        
    }
    AsignaturaControl asignaturaControl=new AsignaturaControl();
    ResourceBundle resourceBundle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
