/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import vista.ventanasInternas.CarreraVista;
import vista.ventanasInternas.AsignaturaVista;
import vista.tablas.TablaAsignaturasVista;
import controlador.AsignaturaControl;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.tools.JavaFileManager.Location;
import modelo.Asignatura;
import vista.tablas.TablaCarrerasVista;
import vista.tablas.TablaProfesoresVista;
import vista.ventanasEliminar.AsignaturaEliminarVista;
import vista.ventanasEliminar.CarreraEliminarVista;
import vista.ventanasEliminar.ProfesorEliminarVista;
import vista.ventanasInternas.ProfesorVista;
import vista.ventanasModificar.AsignaturaModificarVista;
import vista.ventanasModificar.CarreraModificarVista;
import vista.ventanasModificar.ProfesorModificarVista;

/**
 *
 * @author Andy Abad
 */
public class VentanaPrincipalAsignatura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipalAsignatura() {
        this.setIdiomaPredeterminado();
        initComponents();
        this.actualizarLenguaje(resourceBundle);
    }
    private void setIdiomaPredeterminado()
    {
        resourceBundle=ResourceBundle.getBundle("mensajes.mensajes",new Locale("es","EC"));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        jMenu1.setText("Asignatura");

        jMenuItem1.setText("Agregar Asignatura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Listar Asignatura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Modificar Asignatura");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Asignatura");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carrera");

        jMenuItem5.setText("Agregar Carrera");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Listar Carrera");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Modificar Carrera");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Eliminar Carrera");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profesor");

        jMenuItem9.setText("Agregar Profesor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Listar Profesor");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Modificar Profesor");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Eliminar Profesor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configuracion");

        jMenu5.setText("Lenguaje");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Espaniol");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(false);
        jRadioButtonMenuItem2.setText("Ingles");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jRadioButtonMenuItem2);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //av.setLenguajeAsignaturaVentana(resourceBundle);
        av.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        av.setVisible(true);
        jDesktopPane1.add(av);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     
        tav.actualizarTablaAsignatura();
        tav.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jDesktopPane1.add(tav);
        tav.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
     
        cv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jDesktopPane1.add(cv);
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
        pv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jDesktopPane1.add(pv);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        tpv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jDesktopPane1.add(tpv);
        tpv.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        tcv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tcv.setVisible(true);
        jDesktopPane1.add(tcv);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        amv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jDesktopPane1.add(amv);
        amv.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed

        jRadioButtonMenuItem2.setSelected(false);
        resourceBundle=ResourceBundle.getBundle("mensajes.mensajes",new Locale("es","EC"));
        this.actualizarLenguaje(resourceBundle);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        jRadioButtonMenuItem1.setSelected(false);
        resourceBundle=ResourceBundle.getBundle("mensajes.mensajes",new Locale("en","US"));
        this.actualizarLenguaje(resourceBundle);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        cmv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cmv.setVisible(true);
        jDesktopPane1.add(cmv);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        pmv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pmv.setVisible(true);
        jDesktopPane1.add(pmv);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        aev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        aev.setVisible(true);
        jDesktopPane1.add(aev);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        cev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cev.setVisible(true);
        jDesktopPane1.add(cev);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        pev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pev.setVisible(true);
        jDesktopPane1.add(pev);
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    
    private void actualizarLenguaje(ResourceBundle resourceBundle)
    {
        this.setLenguajeVentanaPrincipal(resourceBundle);
        av.setLenguajeAsignaturaVentana(resourceBundle);
        cv.setLenguajeCarreraVentana(resourceBundle);
        pv.setLenguajeProfesorVentana(resourceBundle);
        tav.setLenguajeTablaAsignaturaVista(resourceBundle);
        tcv.setLenguajeTablaCarreraVista(resourceBundle);
        tpv.setLenguajeTablaProfesorVista(resourceBundle);
        amv.setLenguajeAsignaturaModificarVista(resourceBundle);
        cmv.setLenguajeCarreraModificarVentana(resourceBundle);
        pmv.setLenguajeProfesorModificarVentana(resourceBundle);
        aev.setLenguajeAsignaturaEliminarVentana(resourceBundle);
        cev.setLenguajeCarreraEliminarVentana(resourceBundle);
        pev.setLenguajeProfesorEliminarVentana(resourceBundle);
    }
    public void setLenguajeVentanaPrincipal(ResourceBundle resourseBundle)
    {
        jMenu1.setText(resourceBundle.getString("JMENUVP1"));
        jMenu2.setText(resourceBundle.getString("JMENUVP2"));
        jMenu3.setText(resourceBundle.getString("JMENUVP3"));
        jMenu4.setText(resourceBundle.getString("JMENUVP4"));
        jMenu5.setText(resourceBundle.getString("JMENUVP5"));
        
        jRadioButtonMenuItem1.setText(resourceBundle.getString("JRADIOBUTTONVP1"));
        jRadioButtonMenuItem2.setText(resourceBundle.getString("JRADIOBUTTONVP2"));
        
        jMenuItem1.setText(resourceBundle.getString("JMENUITEMVP1"));
        jMenuItem2.setText(resourceBundle.getString("JMENUITEMVP2"));
        jMenuItem3.setText(resourceBundle.getString("JMENUITEMVP3"));
        jMenuItem4.setText(resourceBundle.getString("JMENUITEMVP4"));
        jMenuItem5.setText(resourceBundle.getString("JMENUITEMVP5"));
        jMenuItem6.setText(resourceBundle.getString("JMENUITEMVP6"));
        jMenuItem7.setText(resourceBundle.getString("JMENUITEMVP7"));
        jMenuItem8.setText(resourceBundle.getString("JMENUITEMVP8"));
        jMenuItem9.setText(resourceBundle.getString("JMENUITEMVP9"));
        jMenuItem10.setText(resourceBundle.getString("JMENUITEMVP10"));
        jMenuItem11.setText(resourceBundle.getString("JMENUITEMVP11"));
        jMenuItem12.setText(resourceBundle.getString("JMENUITEMVP12"));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalAsignatura().setVisible(true);
            }
        });
    }
    ResourceBundle resourceBundle;
    AsignaturaControl asignaturaControl=new AsignaturaControl();
    AsignaturaVista av=new AsignaturaVista();
    CarreraVista cv=new CarreraVista();
    ProfesorVista pv=new ProfesorVista();
    TablaAsignaturasVista tav=new TablaAsignaturasVista();
    TablaCarrerasVista tcv=new TablaCarrerasVista();
    TablaProfesoresVista tpv=new TablaProfesoresVista();
    AsignaturaModificarVista amv=new AsignaturaModificarVista();
    CarreraModificarVista cmv=new CarreraModificarVista();
    ProfesorModificarVista pmv=new ProfesorModificarVista();
    AsignaturaEliminarVista aev=new AsignaturaEliminarVista();
    CarreraEliminarVista cev=new CarreraEliminarVista();
    ProfesorEliminarVista pev=new ProfesorEliminarVista();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
