/*
_|}(=[8-p70oi98u7y6t54
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.tablas;

import controlador.AsignaturaControl;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Asignatura;
import modelo.Carrera;
import modelo.Profesor;

/**
 *
 * @author Andy Abad
 */
public class TablaProfesoresVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form TablaProfesoresVista
     */
    public TablaProfesoresVista() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo: ", "Nombre: ", "Correo: ", "Titulo: ", "Fecha de Nacimiento: ", "Anios de Trabajo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Profesor");

        jLabel2.setText("Ingrese el Codigo de Asignatura: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setLenguajeTablaProfesorVista(ResourceBundle resourceBundle)
    {
        this.resourceBundle=resourceBundle;
        jLabel1.setText(resourceBundle.getString("JLABELTPV1"));
        jLabel2.setText(resourceBundle.getString("JLABELTPV2")+": ");
        jButton1.setText(resourceBundle.getString("JBUTTON2"));
        this.setModeloTabla();
        
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo=jTextField1.getText();
        this.actualizarTableCarrera(asignaturaControl.listar().get(asignaturaControl.buscarAsignaturaPorCodigo(codigo)));
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setModeloTabla()
    {
        String[] encabezado=new String[6];
        encabezado[0]=resourceBundle.getString("JTABLETPV1");
        encabezado[1]=resourceBundle.getString("JTABLETPV2");
        encabezado[2]=resourceBundle.getString("JTABLETPV3");
        encabezado[3]=resourceBundle.getString("JTABLETPV4");
        encabezado[4]=resourceBundle.getString("JTABLETPV5");
        encabezado[5]=resourceBundle.getString("JTABLETPV6");
        
        var datos=new Object[0][6];
        
        TableModel modeloTabla=new DefaultTableModel(datos, encabezado);
        jTable1.setModel(modeloTabla);
    }
    public void actualizarTableCarrera(Asignatura asignatura)
    {
        String[] encabezado=new String[6];
        encabezado[0]=resourceBundle.getString("JTABLETPV1");
        encabezado[1]=resourceBundle.getString("JTABLETPV2");
        encabezado[2]=resourceBundle.getString("JTABLETPV3");
        encabezado[3]=resourceBundle.getString("JTABLETPV4");
        encabezado[4]=resourceBundle.getString("JTABLETPV5");
        encabezado[5]=resourceBundle.getString("JTABLETPV6");
        
        var datos=new Object[asignatura.getProfesorList().size()][6];
        int i=0;
        for(Profesor profesor: asignatura.getProfesorList())
        {
            datos[i][0]=profesor.getCodigo();
            datos[i][1]=profesor.getNombre();
            datos[i][2]=profesor.getCorreo();
            datos[i][3]=profesor.getTitulo();
            datos[i][4]=profesor.getDiaNacimiento()+"/"+profesor.getMesNacimiento()
                    +"/"+profesor.getAnioNacimiento();
            datos[i][5]=profesor.getAniosTrabajo();
            i++;
        }
        TableModel modeloTabla=new DefaultTableModel(datos, encabezado);
        jTable1.setModel(modeloTabla);
    }
    AsignaturaControl asignaturaControl=new AsignaturaControl();
    ResourceBundle resourceBundle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
